Transform: 'AWS::Serverless-2016-10-31'
Description: Template to create a Slack Bot Lambda function to report CodeBuild build status

Parameters:

  AppName:
    Type: String
    Description: Application being deployed
    Default: myapp

  SlackHook:
    Type: String
    Description: URL of Slack notification
    NoEcho: True

  CodeBuildNames:
    Type: CommaDelimitedList
    Description: Names of codebuild jobs to be tied to notifications

  ChannelName:
    Type: String
    Description: (Optional) Name of Channel.

Resources:

  SlackHookFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: !Sub "SlackBot for ${AppName}"
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LambdaExecutionRole.Arn
      InlineCode: |
        'use strict'

        const https = require('https')
        const url = require('url')
        
        const CHANNEL = process.env.CHANNEL
        const SLACK_HOOK_URL = process.env.SLACK_HOOK_URL

        const Colors = {
            IN_PROGRESS: "#0000FF",
            SUCEEDED: "#3CB371",
            FAILED: "#FF0000"
        }

        function getColor(status) {
            switch (status) {
                case 'SUCEEDED':
                    return Colors.SUCEEDED
                case 'FAILED':
                    return Colors.FAILED
                default: 
                    return Colors.IN_PROGRESS
            }
        }

        // Handle the CodeBuild CloudWatch Event and post the message to slack so we know the progress of our build.
        function handler(event, context) {
            console.log(JSON.stringify(event))

            const status = event.detail['build-status']
            const startedBy = event.detail['additional-information']['initiator']
            const project = event.detail['project-name']
            const buildId = event.detail['build-id'].split(":").pop()
            const projectUrl = `https://console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/${project}:${buildId}/view/new`
            const time = Math.floor(Date.now() / 1000)

            const payload = {
                channel: CHANNEL,
                username: "CodeBuildBot",
                icon_emoji: ":codebuild:",
                attachments: [{
                    color: getColor(status),
                    author_name: `Started by ${startedBy}`,
                    title: project,
                    title_link: projectUrl,
                    fields: [{
                        title: "Status",
                        value: status,
                        short: false
                    }],
                    footer: "Incoming Webhooks API",
                    footer_icon: "https://a.slack-edge.com/ae7f/img/services/outgoing-webhook_512.png",
                }]
            }
          
            postToSlack(payload, SLACK_HOOK_URL, function (err, results) {
                if (err) return context.fail(err)
                else return context.succeed(results)
            })
        }

        // Post a message to the slack hook.
        function postToSlack(payload, hook_url, done) {
            const slack_hook_url_parts = url.parse(hook_url)

            const options = {
                hostname: slack_hook_url_parts.host,
                port: 443,
                path: slack_hook_url_parts.pathname,
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                }
            }

            console.log(JSON.stringify(options))
          
            var req = https.request(options, function (res) {
                res.setEncoding('utf8')
                res.on('data', function (chunk) {
                    console.log('data')
                    done(null, chunk)
                })
                res.on('end', function () {
                    console.log('end')
                    done(null, null)
                })
            })

            req.on('error', function (err) {
                done(err, null)
            })

            // write data to request body
            req.write(JSON.stringify(payload))
          
           req.end()
        }

        module.exports = { handler }
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - CodeBuild Build State Change
              source:
                - aws.codebuild
              detail:
                project-name: !Ref CodeBuildNames
                build-status:
                  - IN_PROGRESS
                  - SUCCEEDED
                  - FAILED
                  - STOPPED
      Environment:
        Variables:
          SLACK_HOOK_URL: !Ref SlackHook
          CHANNEL: !Ref ChannelName

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: SlackBotLogAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: '*'